# Generated by Django 3.2.7 on 2021-10-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='owner',
        ),
    ]
