# Generated by Django 3.2.7 on 2021-10-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apps',
        ),
    ]
